### ISSUE TITLE
Database bug: If I sign up twice for one same username but 2 different email address, it should have given me the error.

### ISSUE THREAD

**Issue by QinxinTian** [TheNergaL/foodapp#85] opened 2017-11-05 03:49 UTC
Then I won't know which email address that account belonged to.
[Screen Capture 6.mov.zip](https://github.com/TheNergaL/foodapp/files/1443738/Screen.Capture.6.mov.zip)

**Comment by doyom123** [comment] 2017-11-05 14:17
Duplicate of #87

**Closed as completed by doyom123** 2017-11-05 14:17 UTC
