### ISSUE TITLE
Bug: Database isn't implemented well. The same email address can be registered for twice with different user name and both username can then be used for logging in.

### ISSUE THREAD

**Issue by QinxinTian** [TheNergaL/foodapp#86] opened 2017-11-05 04:39 UTC
[Screen Capture 8.mov.zip](https://github.com/TheNergaL/foodapp/files/1443775/Screen.Capture.8.mov.zip)

**Comment by doyom123** [comment] 2017-11-05 14:17
Duplicate of #87

**Closed as completed by doyom123** 2017-11-05 14:17 UTC
